### ISSUE TITLE
Gandy Young Blitter Angular Lab

### ISSUE THREAD

**Issue by gandyland** [ga-wdi-exercises/angular_blitter_lab#10]
https://github.com/gandyland/blitter_angular

completeness: 1 or 2
comfort: 2

To be honest I'm not sure if I even got this one working. We've done a few labs this week and I can't remember what issues I was having with this one.

**Comment by nolds9** [comment]
:+1: Good job on this, would encourage you to come back to this and implement the rest of the outlined features.
