### ISSUE TITLE
Blitter Lab - James Graham

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/angular_blitter_lab#2]
https://github.com/wombatdev/angular-blitter-lab

I thought blitter was pretty much a duplicate of grumblr so I mostly copied and pasted for about 20 min. Afterwards I started trying to use a real API--Sunlight Capital Words. You can search for words that come up in Congress at localhost:8080/#/words:
https://github.com/wombatdev/sunlight-api-angular

```
Comfort: 5/5
Completeness: 4/5 (no bonuses)
```

**Comment by amaseda** [comment]
:+1: props on taking it to the next level
